[package]
name = "server"
version = "0.1.0"
edition = "2024"
authors = ["Alex E <igsalexcodes@gmail.com>"]
repository = "https://github.com/aellul27/QUICInput"

[dependencies]
shared = { path = "../shared" }